### ISSUE TITLE
ISBN 979-8833029008 fails validation

### ISSUE THREAD

**Issue by dwightkelly** [inventaire/isbn3#10]
The ISBN 9798833029008 fails validation. 979 is the new prefix. 9798582175339  and 9798986359403 works.

**Comment by maxlath** [comment]
As 979-8-8330-2900-8 is part of a range that was published recently on isbn-international.org, validation would fail in `isbn3 v1.1.19` but should pass in the latest version (`isbn3 v1.1.24`). The ISBN ranges used by `isbn3` are automatically updated every month, and that update is published in a new patch version. Can you confirm that updating fixes the issue?

**Comment by dwightkelly** [comment]
Yes, thank you
