### ISSUE TITLE
Isbn invalid

### ISSUE THREAD

**Issue by Roman991** [inventaire/isbn3#15]
`9790041811529` is a valid isbn13, but isbn3 marks it as `invalid ISBN`

**Comment by rkeytacked** [comment]
There is no ISBN group assigned to 979-0…
See also on [Wikipedia](https://en.wikipedia.org/wiki/ISBN):

> Within the 979 prefix element, the registration group 0 is reserved for compatibility with [International Standard Music Numbers](https://en.wikipedia.org/wiki/International_Standard_Music_Number) (ISMNs), but such material is not actually assigned an ISBN.[[41]](https://en.wikipedia.org/wiki/ISBN#cite_note-6th_edition_Users'_Manual-46) The registration groups within prefix element 979 that have been assigned are 8 for the United States of America, 10 for France, 11 for the Republic of Korea, and 12 for Italy.

**Comment by Roman991** [comment]
But formally its correct, also the check digit is OK (also there's an existing product behind this code, and its a book).
What a strange case

**Comment by rkeytacked** [comment]
Well, yes it is a correct EAN-13, but it is not an ISBN. It is an ISMN, see https://en.wikipedia.org/wiki/International_Standard_Music_Number
