### ISSUE TITLE
 TypeError: Cannot read property '6' of undefined

### ISSUE THREAD

**Issue by korzo** [inventaire/isbn3#7]
When validating 4036526651248, I got `TypeError: Cannot read property '6' of undefined`.
The root of this error is missing check if `groupsMap[prefix]` is not undefined in 
https://github.com/inventaire/isbn3/blob/master/lib/get_group.js#L16

**Comment by maxlath** [comment]
thanks for reporting! fixed (ad887bf) and published in `v1.1.1`
